{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourceconfigapi",
    "module": "resourceconfigapi-fabric",
    "version": "1.21-2.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.4.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.4.jar",
          "size": 632277,
          "sha512": "bcfd2bf433f06557884eae8620c024354c5d4c6c29104a6d23424defb48989449f48870dd51c805d312f08bc0721922770e1c06082e85a4491d4deac36ce7727",
          "sha256": "db09b3fba80a7439bf236e797c1f47364616e09ad5a6e74dc10608eddc07c136",
          "sha1": "cffcaa4b6c7ced64faba9ed77b942b80f0395a11",
          "md5": "5fff9da62d7ba7fa2a85beda50f0487d"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21.1",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.4.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.4.jar",
          "size": 632277,
          "sha512": "bcfd2bf433f06557884eae8620c024354c5d4c6c29104a6d23424defb48989449f48870dd51c805d312f08bc0721922770e1c06082e85a4491d4deac36ce7727",
          "sha256": "db09b3fba80a7439bf236e797c1f47364616e09ad5a6e74dc10608eddc07c136",
          "sha1": "cffcaa4b6c7ced64faba9ed77b942b80f0395a11",
          "md5": "5fff9da62d7ba7fa2a85beda50f0487d"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21.1",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.4-sources.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.4-sources.jar",
          "size": 196430,
          "sha512": "af5d07e2be8056277274512f62cb3d47e4ecc1bfc814bbed5b0f31a5094bb2f3b6df2ba7bd9441988ca80a5ef1bedcb97c2e0e351bec2db53c8c4b3b67293722",
          "sha256": "495ead349e749826b5204d35eae0b7d3bf52c49ca2ce000cd6b94ddafa278ca8",
          "sha1": "834dafb0771b379c5dcc2bc331a81d4c60c47b38",
          "md5": "c9c5b1e8cad8f136129b6022b3ccd1b6"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21.1",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.4-javadoc.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.4-javadoc.jar",
          "size": 207122,
          "sha512": "ba4d615f2a5bbb4df455f5e78fa038864e104fad852533fdfd09c2e1cc835137ea3a464db9f9486921be2deaf88ef6fc5d6f135a78c9184ca0294334f38fcd91",
          "sha256": "3b78237d8ac9f458b331e3ea4c692b415db29597d39bf9bd2c00c927c1476bc9",
          "sha1": "5f943cfcb666d984188dfa2d7364be111653d963",
          "md5": "6cd7b5cf4ef002815f1788ffaef5db01"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21.1",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.4"
        }
      ]
    }
  ]
}
