{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourcelibrary",
    "module": "resourcelibrary-neoforge",
    "version": "1.21-2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "resourcelibrary-neoforge-1.21-2.0.0.jar",
          "url": "resourcelibrary-neoforge-1.21-2.0.0.jar",
          "size": 223177,
          "sha512": "ca2c563cf6c588afbbc8582e3e506afeffebb40bc4e421cafa781cb9fee98b28896d3f416390e8b78a1194fafe1e6c609ca02e01fd495698a3aa98f93c224689",
          "sha256": "8b368c3066b17efcc0b045c3d63c02a5805480d20d5aec1244cc7531fb1f7777",
          "sha1": "69830f116dc77451faf0974680998dd8a7fbf4a8",
          "md5": "48d7baec8d14eb91d939f3e880c149a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourcelibrary-neoforge-1.21-2.0.0.jar",
          "url": "resourcelibrary-neoforge-1.21-2.0.0.jar",
          "size": 223177,
          "sha512": "ca2c563cf6c588afbbc8582e3e506afeffebb40bc4e421cafa781cb9fee98b28896d3f416390e8b78a1194fafe1e6c609ca02e01fd495698a3aa98f93c224689",
          "sha256": "8b368c3066b17efcc0b045c3d63c02a5805480d20d5aec1244cc7531fb1f7777",
          "sha1": "69830f116dc77451faf0974680998dd8a7fbf4a8",
          "md5": "48d7baec8d14eb91d939f3e880c149a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourcelibrary-neoforge-1.21-2.0.0-sources.jar",
          "url": "resourcelibrary-neoforge-1.21-2.0.0-sources.jar",
          "size": 191257,
          "sha512": "d75b64969f7bdf313063caf941b8f8f9dbc2ff8d43e1f723c5f45797e983e0ca06f2f4633a08c5f48846f497fc8553be318ffd2d81271be70acc3a61c4abc05b",
          "sha256": "f20eacd1b562704d8ebecf6cc6b96d05b5482818d171a4dedec292bbacd388f3",
          "sha1": "96d96444de6d2dfc087c4c6147ac039f98bf1866",
          "md5": "d284599bb74525dbdaae5a12d738a573"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourcelibrary-neoforge-1.21-2.0.0-javadoc.jar",
          "url": "resourcelibrary-neoforge-1.21-2.0.0-javadoc.jar",
          "size": 257393,
          "sha512": "35d218931eb5a7bbf1dbb7dd53d2d095d51a308c002f8352e20bfb68738c1153b069bceb77e003f62bb88c778dda18390d7d69a9096db02df028fc4b2549e210",
          "sha256": "f615bd9ebaa31b0a3dae8a605da3df1f472c5bd24fe1e4f130c2bc4d3986278a",
          "sha1": "187b92444bb43810aacd42e195364bf8e4c5a408",
          "md5": "4510015723c09537a08184b8ef893203"
        }
      ]
    }
  ]
}
