{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourceconfigapi",
    "module": "resourceconfigapi-fabric",
    "version": "1.21-2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.1.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.1.jar",
          "size": 634864,
          "sha512": "168811967eaa1eed899b7a5172bf59fd96eaa2e685cdad64be21cf5b292419870f55aa0ca541aabc88b861e3ec75af719a76865a2f2f697430185aa8560f608c",
          "sha256": "2c78d6f8a5fb45ae76b58587c6a979edec1a2264615e010b5dcb34ac0a8d42fd",
          "sha1": "bb06c214c1b2e3836de4faa97332a12cdca96e05",
          "md5": "fedee11d22bb88b19bbc49c59ad3a8a6"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.1"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.1"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21",
          "version": "1.21-2.1.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.7+1.21"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.1.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.1.jar",
          "size": 634864,
          "sha512": "168811967eaa1eed899b7a5172bf59fd96eaa2e685cdad64be21cf5b292419870f55aa0ca541aabc88b861e3ec75af719a76865a2f2f697430185aa8560f608c",
          "sha256": "2c78d6f8a5fb45ae76b58587c6a979edec1a2264615e010b5dcb34ac0a8d42fd",
          "sha1": "bb06c214c1b2e3836de4faa97332a12cdca96e05",
          "md5": "fedee11d22bb88b19bbc49c59ad3a8a6"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.1"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.1"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21",
          "version": "1.21-2.1.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.1-sources.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.1-sources.jar",
          "size": 198119,
          "sha512": "5d3c5847171c6e37ec59776636257fde5241e057ca9bf9edf9238476eb0ccc8fd539910d8942ec11722a6c1835b17020cb54592079ac1aac7fa7c272fb5116d1",
          "sha256": "60030f0a8b5ab7c21b72c15696a63e634e55aefa7f80d939b11f8c48eb5d9686",
          "sha1": "b52234e533b34cb89f7a25f373c737caba7b0ee1",
          "md5": "0ae72f87eb6bc42d54c73bce5468c2ab"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.1"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.1"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21",
          "version": "1.21-2.1.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.1-javadoc.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.1-javadoc.jar",
          "size": 218017,
          "sha512": "796c9b22d18c7e08a02d8421e42fe9e7f45a2e87517b07a6782e426f28643a4682be6731d52541717df0c6f5242c607cb31ce56d262be53156fd58faaed94e3f",
          "sha256": "e82c091265ff7a568551e3f41fe1de9f868895cd075238b6ca5070c16cfdfcd3",
          "sha1": "8d480560683f3c2f142d466ff985e66be75b0c37",
          "md5": "2fd8890d572da0711d732b0f27a3811f"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.1"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.1"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21",
          "version": "1.21-2.1.1"
        }
      ]
    }
  ]
}
