{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourceconfigapi",
    "module": "resourceconfigapi-neoforge",
    "version": "1.21-2.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "resourceconfigapi-neoforge-1.21-2.1.3.jar",
          "url": "resourceconfigapi-neoforge-1.21-2.1.3.jar",
          "size": 214093,
          "sha512": "728528efbedbcd0f75c5fd44e69c7861f4341b58a9fbe3952bc4d8f5d7c8fb601ca51f8be3692cd114c1696e1609ce266026ffef5f01b3d31b4580a708b9627c",
          "sha256": "1d81b900e97149154b3b1182ec5d80f1832c28616c8b167be04704c0ae17c5fd",
          "sha1": "549615b302804ccb05312b6fab56a00a783a4c08",
          "md5": "758ff49ef825ea0110d6f7f5242b730c"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge",
          "version": "1.21-2.1.3"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge-1.21.1",
          "version": "1.21-2.1.3"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-neoforge-1.21-2.1.3.jar",
          "url": "resourceconfigapi-neoforge-1.21-2.1.3.jar",
          "size": 214093,
          "sha512": "728528efbedbcd0f75c5fd44e69c7861f4341b58a9fbe3952bc4d8f5d7c8fb601ca51f8be3692cd114c1696e1609ce266026ffef5f01b3d31b4580a708b9627c",
          "sha256": "1d81b900e97149154b3b1182ec5d80f1832c28616c8b167be04704c0ae17c5fd",
          "sha1": "549615b302804ccb05312b6fab56a00a783a4c08",
          "md5": "758ff49ef825ea0110d6f7f5242b730c"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge",
          "version": "1.21-2.1.3"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge-1.21.1",
          "version": "1.21-2.1.3"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-neoforge-1.21-2.1.3-sources.jar",
          "url": "resourceconfigapi-neoforge-1.21-2.1.3-sources.jar",
          "size": 193009,
          "sha512": "dd005488a3631b6e476666687f772062cf0b08f273317170f59fcfd6c539dda568cc71fdc8834d648a567d9949282f5b1285cc05398c6080f3eb59041f551cb8",
          "sha256": "465262d3dd47c638fb8ef7762bb7f31e9b57064f16e773539b483cbb5fff7ed4",
          "sha1": "41afb23538d845b024db0662b8f4977905f6185f",
          "md5": "fc22c678d817d3a9c4892b4454a6db2b"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge",
          "version": "1.21-2.1.3"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge-1.21.1",
          "version": "1.21-2.1.3"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-neoforge-1.21-2.1.3-javadoc.jar",
          "url": "resourceconfigapi-neoforge-1.21-2.1.3-javadoc.jar",
          "size": 212812,
          "sha512": "2ac6be4c16a85cebb36b694bb24c354b4612447856b178c19e7ff0aec3cac5f5453829438b8fdf27cbe4114a1be153c2789db4e655ac6652eacab6f371994c57",
          "sha256": "49826b2d81f14512c31db470843e9c85cc5563b76e8d0f56a75fd9bdb555d81f",
          "sha1": "a80e8238890d439dd12b3846d2e25aa668d95f0a",
          "md5": "7f97049b4b50ff3e6305ab85265e4aba"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge",
          "version": "1.21-2.1.3"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge-1.21.1",
          "version": "1.21-2.1.3"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.3"
        }
      ]
    }
  ]
}
