{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourceconfigapi",
    "module": "resourceconfigapi-neoforge",
    "version": "1.20.5+1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "resourceconfigapi-neoforge-1.20.5+1.0.0.jar",
          "url": "resourceconfigapi-neoforge-1.20.5+1.0.0.jar",
          "size": 192313,
          "sha512": "102e145a027886d5dcb18fadc2bc8bcf781017e268168f5828d826ec436d2d4adb09fa4b6d894823d7fc7dfc941af7a5b2d312ea47288825fb7a9614df18ed4d",
          "sha256": "efbd131484c1a93f646a7080662462c2bd79f6ea999d670139201f4aa91a72bc",
          "sha1": "1028c0ed66d2e9f5f523bde3de2f5e1e523daae9",
          "md5": "0a7a86cfbc767c46375b07183ec741ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-neoforge-1.20.5+1.0.0.jar",
          "url": "resourceconfigapi-neoforge-1.20.5+1.0.0.jar",
          "size": 192313,
          "sha512": "102e145a027886d5dcb18fadc2bc8bcf781017e268168f5828d826ec436d2d4adb09fa4b6d894823d7fc7dfc941af7a5b2d312ea47288825fb7a9614df18ed4d",
          "sha256": "efbd131484c1a93f646a7080662462c2bd79f6ea999d670139201f4aa91a72bc",
          "sha1": "1028c0ed66d2e9f5f523bde3de2f5e1e523daae9",
          "md5": "0a7a86cfbc767c46375b07183ec741ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-neoforge-1.20.5+1.0.0-sources.jar",
          "url": "resourceconfigapi-neoforge-1.20.5+1.0.0-sources.jar",
          "size": 181788,
          "sha512": "a48c090f488556307d78ab10b11c63994d39953744a7b4beb26c8b07781bc88591931d398126a109fbdcd01db9f7f72df8b2c39365e43e5088f3e8af91570468",
          "sha256": "64494559edacfa32f06d378f0703d272be98264124d246f22767a094238e02a2",
          "sha1": "721db5c5b610369e178f7f8ade867a420bd28517",
          "md5": "08882d9f5c2a41b932d249e5a0f0ca34"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-neoforge-1.20.5+1.0.0-javadoc.jar",
          "url": "resourceconfigapi-neoforge-1.20.5+1.0.0-javadoc.jar",
          "size": 173811,
          "sha512": "38e7113922f265ccea4e7c83e9aa7289ee45600f4b57112376995c9bae5de275244b6a7dc76dd70405597d5d52c3b59d181975ecf26acd180b87a0e8f187b06c",
          "sha256": "790dd84420840c92ae71503a6e945e8d9645bd952f918d6ae80ee71c92eef096",
          "sha1": "d30d9fea7cc249698c65398adb96f6704418ed43",
          "md5": "66f0df7280022d6853ec7cd0197932bc"
        }
      ]
    }
  ]
}
