{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourceconfigapi",
    "module": "resourceconfigapi-fabric",
    "version": "1.20.5+1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.6+1.20.5"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.20.5+1.0.0.jar",
          "url": "resourceconfigapi-fabric-1.20.5+1.0.0.jar",
          "size": 437059,
          "sha512": "c1f78d380b7e64c7d0259e26d4d82e68bee667a409be164dace74bd20470349040ef0fa29c46bc0d69b4dbd6497a06827afe493360a1a3895a7e12b245c96697",
          "sha256": "560e1ba3fb8cee367fcaaf44a1b43a89e44befd9bd83d8fb416190268d7cb80b",
          "sha1": "62e7cc8ac080ac98b36ebd125c76de9f1a158413",
          "md5": "9adf717c529bff0a7781723abfb2f13d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.6+1.20.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.20.5+1.0.0.jar",
          "url": "resourceconfigapi-fabric-1.20.5+1.0.0.jar",
          "size": 437059,
          "sha512": "c1f78d380b7e64c7d0259e26d4d82e68bee667a409be164dace74bd20470349040ef0fa29c46bc0d69b4dbd6497a06827afe493360a1a3895a7e12b245c96697",
          "sha256": "560e1ba3fb8cee367fcaaf44a1b43a89e44befd9bd83d8fb416190268d7cb80b",
          "sha1": "62e7cc8ac080ac98b36ebd125c76de9f1a158413",
          "md5": "9adf717c529bff0a7781723abfb2f13d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.20.5+1.0.0-sources.jar",
          "url": "resourceconfigapi-fabric-1.20.5+1.0.0-sources.jar",
          "size": 185475,
          "sha512": "2d57bf9ea5b56ac8c5b92dd3b9111a43966e5c26f312b5480235d40074e7101e90cff2fe43349b2019ffa9a314a64c1ccf9b871ce08beaf958f436cd408536e9",
          "sha256": "027a56d2e40f99aeb104de2599ad599d02e16d74e6687905da69c8b16b631d34",
          "sha1": "a86fea3f3ee55cb2953448604e493214003f84ab",
          "md5": "3bdf4248eb1fa18bcba38eaea27fa4bc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.20.5+1.0.0-javadoc.jar",
          "url": "resourceconfigapi-fabric-1.20.5+1.0.0-javadoc.jar",
          "size": 174280,
          "sha512": "703e0fcd5df7f0225f657f13297f0b726a6ffebccff0fc833805002ac7d8370e84d4ad0f40d5765e2d14e5a6945d3e247f47f78095265944bd8baf8310dc1c80",
          "sha256": "65ad514b86d8183a77ec6bfe3630954dace55af3a9ddc068cb31d978abfa537b",
          "sha1": "c85baa7ad2718ab37d09ac59c9bb3a7f112106c3",
          "md5": "4d629d1d3d97d92f946839a4f86d0a42"
        }
      ]
    }
  ]
}
