{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourceconfigapi",
    "module": "resourceconfigapi-fabric",
    "version": "1.20.5+1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.6+1.20.5"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.20.5+1.0.0.jar",
          "url": "resourceconfigapi-fabric-1.20.5+1.0.0.jar",
          "size": 437065,
          "sha512": "53347a4cb4574373aa7209ed740d4c5c6d0ae36d779a138a573c3d3354d97840c9db5b83aeb3df554c82eec6429f5ffe12844d616dd3ab7dc6d284eb001e8c4e",
          "sha256": "5b7a7ff25e116d62c9b27c2b4718d1d85d4e42886bf8ed417cea2925fc41af6b",
          "sha1": "6f31b6e95bfb94e0f612014b97c74a91a6b4c0c2",
          "md5": "cc12b8d1cdf4fb90dfaa2c40602db634"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.6+1.20.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.20.5+1.0.0.jar",
          "url": "resourceconfigapi-fabric-1.20.5+1.0.0.jar",
          "size": 437065,
          "sha512": "53347a4cb4574373aa7209ed740d4c5c6d0ae36d779a138a573c3d3354d97840c9db5b83aeb3df554c82eec6429f5ffe12844d616dd3ab7dc6d284eb001e8c4e",
          "sha256": "5b7a7ff25e116d62c9b27c2b4718d1d85d4e42886bf8ed417cea2925fc41af6b",
          "sha1": "6f31b6e95bfb94e0f612014b97c74a91a6b4c0c2",
          "md5": "cc12b8d1cdf4fb90dfaa2c40602db634"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.20.5+1.0.0-sources.jar",
          "url": "resourceconfigapi-fabric-1.20.5+1.0.0-sources.jar",
          "size": 185478,
          "sha512": "de0da3332acd4e8a49d3ea6b0a608893abc5f4e4c12d20703149df91343d00294f5fa4cb20404148da788270e600e8aba3c6eb6bb1630019c7426b9632a570ce",
          "sha256": "0c61140f3a5e12e9126b41a42e686e14d1e85836c86a70735470fcccc7f4783b",
          "sha1": "3b265493e72abbeb637e4657d2dd8d6c77c7537e",
          "md5": "09a30c2223466b4de57777f505d58517"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.20.5+1.0.0-javadoc.jar",
          "url": "resourceconfigapi-fabric-1.20.5+1.0.0-javadoc.jar",
          "size": 174280,
          "sha512": "40fd66c546751ed888c2d3706253859e68f777aa38ba18edfa4d3c6d8fe3a3ef12f2e7563a02719ed429282247ac9706a79ec6f43be9806e08bc46718e918d47",
          "sha256": "53de35c5002e32bcfa4fc20f351b1130f0fd43db60c22f91ffb88104fedf2137",
          "sha1": "ad7a7884c38167bb975e919d0d6bf7da5e836f7f",
          "md5": "1f307e2fe9fd030f604c9d8cba0b3a04"
        }
      ]
    }
  ]
}
