{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourcelibrary",
    "module": "resourcelibrary-neoforge",
    "version": "1.20.5-1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "resourcelibrary-neoforge-1.20.5-1.3.1.jar",
          "url": "resourcelibrary-neoforge-1.20.5-1.3.1.jar",
          "size": 193942,
          "sha512": "bbd5a7035e5a612e217b6a30cbc1a3d2811f35d3b0e4764b6699250bce38f86c62a4abb07ebba30050b2ae0a44897a917abd9335b6802836aa8891222e000b16",
          "sha256": "02a6dbcd601f038099406ab23410fa72bd32ad07a1ad878549c75be3309ad9ab",
          "sha1": "42d653ac5395cb55e31c341707d33462ce973845",
          "md5": "0288ef58920e878e5b8eff8aa7e22267"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourcelibrary-neoforge-1.20.5-1.3.1.jar",
          "url": "resourcelibrary-neoforge-1.20.5-1.3.1.jar",
          "size": 193942,
          "sha512": "bbd5a7035e5a612e217b6a30cbc1a3d2811f35d3b0e4764b6699250bce38f86c62a4abb07ebba30050b2ae0a44897a917abd9335b6802836aa8891222e000b16",
          "sha256": "02a6dbcd601f038099406ab23410fa72bd32ad07a1ad878549c75be3309ad9ab",
          "sha1": "42d653ac5395cb55e31c341707d33462ce973845",
          "md5": "0288ef58920e878e5b8eff8aa7e22267"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourcelibrary-neoforge-1.20.5-1.3.1-sources.jar",
          "url": "resourcelibrary-neoforge-1.20.5-1.3.1-sources.jar",
          "size": 174185,
          "sha512": "a454c0f34faa8a0695db349decf1fd1bace3ac77cf288d3e2d39bc1af7248590b2c9f404e6058438876be3e035b5d3fd3ea4b1eb9913bfa4f49d8498531667dc",
          "sha256": "4d224c9b130c54c696571d701a905c7dd89df621b8b160aeb877deca0ad0d278",
          "sha1": "86ff4d5698d57115caf213f8ccfd2804e333b7fa",
          "md5": "82b954c82e715b533e4fa82ab44fa05b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourcelibrary-neoforge-1.20.5-1.3.1-javadoc.jar",
          "url": "resourcelibrary-neoforge-1.20.5-1.3.1-javadoc.jar",
          "size": 182979,
          "sha512": "125d108b99590bb40bc98436d8c6f77f55ade53325719205df2e86a1feb036d1a94bdcd01fdd1f20ef9c37d6d3894d63e1442c2041afe88a69c9c51ecd6a0670",
          "sha256": "6de8cadafc2cd0eb3592550a7a0683c2ee52f5d7c759f88646ad3575ee7984ba",
          "sha1": "75707c8eb905c9dd1ad8caec8d74ed4041bf0a91",
          "md5": "824485a9cb4c96a4ef36e87c3ed83fb1"
        }
      ]
    }
  ]
}
