{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourceconfigapi",
    "module": "resourceconfigapi-fabric",
    "version": "1.21-2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.7+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.0.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.0.jar",
          "size": 634864,
          "sha512": "3b9abe0db24e6dfdbfa0ab8f3acb9b8765a0b0f48f11dd5fea275d0fb79d3ebebdeaeb91f0c9924689238fc7dc4ed1170fb66927ea716131572c5aa0924c3994",
          "sha256": "cac36de454402e753f8f30adc74c8242f6b7d3d7833f463fe7615c45776309db",
          "sha1": "b6689be4accea5136b518a9c4a156edd5c859579",
          "md5": "c7e0353a0dc1c8d34048812d87b527e9"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.0"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.0"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21",
          "version": "1.21-2.1.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.7+1.21"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.0.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.0.jar",
          "size": 634864,
          "sha512": "3b9abe0db24e6dfdbfa0ab8f3acb9b8765a0b0f48f11dd5fea275d0fb79d3ebebdeaeb91f0c9924689238fc7dc4ed1170fb66927ea716131572c5aa0924c3994",
          "sha256": "cac36de454402e753f8f30adc74c8242f6b7d3d7833f463fe7615c45776309db",
          "sha1": "b6689be4accea5136b518a9c4a156edd5c859579",
          "md5": "c7e0353a0dc1c8d34048812d87b527e9"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.0"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.0"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21",
          "version": "1.21-2.1.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.0-sources.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.0-sources.jar",
          "size": 198119,
          "sha512": "25ad36fc2e0916cce93c80bade1f6ece281923ab612500baeb6526b61673da1335127ad2e513d564a9b7ed34db62498e1d6c652dd5c6e4550bcea24aefd59b17",
          "sha256": "7288705eea23fe4816536ac6e54018817b5847806457cf3af09cc59e7203bbbd",
          "sha1": "beff8a674d24cf449893382f8635fac7b8d03ae5",
          "md5": "9afb7459087a6e485cf30ebc59208676"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.0"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.0"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21",
          "version": "1.21-2.1.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.0-javadoc.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.0-javadoc.jar",
          "size": 218041,
          "sha512": "3e7007a39fd7fc3faa320770783cf452bad123332b37843c5969f97337f9a4e66e13caeb2314096546171baa7e13af6d1deb28d843a9ffc0072488ab5289766b",
          "sha256": "ffd1ee8622ba9a6cdc4e104c66bed04e0d5cddbe5533614b17d3b37375246d99",
          "sha1": "c9873cfe18c6216ec0f6dd54f46d7fcb114726ad",
          "md5": "091997cbf65347a568bd29fa5a8af34c"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.0"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.0"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21",
          "version": "1.21-2.1.0"
        }
      ]
    }
  ]
}
