{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourceconfigapi",
    "module": "resourceconfigapi-forge",
    "version": "1.21-2.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "resourceconfigapi-forge-1.21-2.1.4.jar",
          "url": "resourceconfigapi-forge-1.21-2.1.4.jar",
          "size": 212044,
          "sha512": "0c6792770b3247216e31e0ca91893662099e2bec3a46825fb45914325fba3f64f2164f2f74c1c7eea68964c984db9ebf830777b3ed85bc911c4ce130d3b200ff",
          "sha256": "b2671a0f55adad45b4023e347d002311646056da7c17e5da0ab6107865393eee",
          "sha1": "d861a52b795237ced825030a6261d57b3224d98d",
          "md5": "90f5fe13c525be004becc7cd91f0749c"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-forge",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-forge-1.21.1",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "strictly": "5.0.4",
            "requires": "5.0.4"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.1-52.0.2_mapped_official_1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-forge-1.21-2.1.4.jar",
          "url": "resourceconfigapi-forge-1.21-2.1.4.jar",
          "size": 212044,
          "sha512": "0c6792770b3247216e31e0ca91893662099e2bec3a46825fb45914325fba3f64f2164f2f74c1c7eea68964c984db9ebf830777b3ed85bc911c4ce130d3b200ff",
          "sha256": "b2671a0f55adad45b4023e347d002311646056da7c17e5da0ab6107865393eee",
          "sha1": "d861a52b795237ced825030a6261d57b3224d98d",
          "md5": "90f5fe13c525be004becc7cd91f0749c"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-forge",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-forge-1.21.1",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-forge-1.21-2.1.4-sources.jar",
          "url": "resourceconfigapi-forge-1.21-2.1.4-sources.jar",
          "size": 192412,
          "sha512": "b812edbe4205d44beb142bee64130e33624808adb1f6206a7109337558ba415c3dd079fc784cd745aa1a8459073c23ee97d369ef037ff259e532d7f6be1b041f",
          "sha256": "8a3642218c1dfb879f9bb5fe0a73fd552842a5828ae03788724abe128f9f8344",
          "sha1": "7b001d022bee64901d36fa1cc2e4fc550fba9170",
          "md5": "99fa8cfcb81851d94259ac534607986d"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-forge",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-forge-1.21.1",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-forge-1.21-2.1.4-javadoc.jar",
          "url": "resourceconfigapi-forge-1.21-2.1.4-javadoc.jar",
          "size": 203534,
          "sha512": "12a0191fda0bd43366506c94942ff040a80f030f93c5e3c439a8da203b6a3f562ffcffb083ba5c63c5f0242ddcc10172117ef66d69f125ad96b8431bfad0db74",
          "sha256": "1364c0d248c47f656c95882c3bf23bc3bd058f33c2ae6e9d7ede807b8f61a340",
          "sha1": "3a93225e72e37a59b5c3abc2bd82f2dd709cf3e8",
          "md5": "1455c67e444e810487bf28a1495f8501"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-forge",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-forge-1.21.1",
          "version": "1.21-2.1.4"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.4"
        }
      ]
    }
  ]
}
