{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourceconfigapi",
    "module": "resourceconfigapi-neoforge",
    "version": "1.21-2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "resourceconfigapi-neoforge-1.21-2.1.2.jar",
          "url": "resourceconfigapi-neoforge-1.21-2.1.2.jar",
          "size": 214089,
          "sha512": "a8015534bbf3afbf4b172b1504af80c8ae8e54b9f2da1558569337acff4f3c3573730d4a34e8ba069f107f50cbc99906fdeecebcac72a4196896e944d14270a2",
          "sha256": "148c2397aa3bdae73204529464d0364a4392ca9a87d82fa15f685ac2739cd0c8",
          "sha1": "9e5f38b71832bc8afc6feca3ef20bb0cc0a577fc",
          "md5": "b62572ad00acd3df82ac2852ea5bf41b"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge-1.21.1",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-neoforge-1.21-2.1.2.jar",
          "url": "resourceconfigapi-neoforge-1.21-2.1.2.jar",
          "size": 214089,
          "sha512": "a8015534bbf3afbf4b172b1504af80c8ae8e54b9f2da1558569337acff4f3c3573730d4a34e8ba069f107f50cbc99906fdeecebcac72a4196896e944d14270a2",
          "sha256": "148c2397aa3bdae73204529464d0364a4392ca9a87d82fa15f685ac2739cd0c8",
          "sha1": "9e5f38b71832bc8afc6feca3ef20bb0cc0a577fc",
          "md5": "b62572ad00acd3df82ac2852ea5bf41b"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge-1.21.1",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-neoforge-1.21-2.1.2-sources.jar",
          "url": "resourceconfigapi-neoforge-1.21-2.1.2-sources.jar",
          "size": 193009,
          "sha512": "b450739e85faccae0b15ba77606296653c02191177c9c7a3260dc52c0a1cbde350b581bbd70ee42721eddbc8d3ec341e0aae3c796674f236777933605795ff94",
          "sha256": "216a9ee1ef7a26c48a01d168f865380405298437167dc314f7997bd57e9bdb66",
          "sha1": "aaa42dd18c5d8f81006c9cf1c47fdf20b0eb2f13",
          "md5": "e72b854acd738bbf7ec92ee82b15d1fa"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge-1.21.1",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-neoforge-1.21-2.1.2-javadoc.jar",
          "url": "resourceconfigapi-neoforge-1.21-2.1.2-javadoc.jar",
          "size": 212726,
          "sha512": "aa9b994454f297ed1cd6bc527762040237acf92611205a3a185e59fa3ccf7642fa1c44a98d1f1a7ecbccbb96e442e58297c0ba2989357b71331a92829754c9bd",
          "sha256": "54b6e8e25a9a3ee496b8cfb1f4f95f1b2ccce19db81fc949d7f26905580ae90a",
          "sha1": "5d09f88d06d65dea4e649828fd8f1795ea2435e9",
          "md5": "3f59029ac31b8f29e10901445f828fa5"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-neoforge-1.21.1",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.2"
        }
      ]
    }
  ]
}
