{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourceconfigapi",
    "module": "resourceconfigapi-fabric",
    "version": "1.21-2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.2.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.2.jar",
          "size": 632274,
          "sha512": "a83a60f46bfbb7091bd1ed2f00c37038841dac04c174f7c073285075b9889460fbf08bf2e5b4fd0beb08bfd02ddde23aa1ad426e4f8c3521a54887e58928f5a0",
          "sha256": "e291a709a89c7538ae030765b067875366fa2dc7e755ea82354649b2fa471413",
          "sha1": "e0d7a9dc27ba322ded458b66abb33c1a987269ec",
          "md5": "8672fe8a51fc246fe8bea8b8d4e88c83"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21.1",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.2.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.2.jar",
          "size": 632274,
          "sha512": "a83a60f46bfbb7091bd1ed2f00c37038841dac04c174f7c073285075b9889460fbf08bf2e5b4fd0beb08bfd02ddde23aa1ad426e4f8c3521a54887e58928f5a0",
          "sha256": "e291a709a89c7538ae030765b067875366fa2dc7e755ea82354649b2fa471413",
          "sha1": "e0d7a9dc27ba322ded458b66abb33c1a987269ec",
          "md5": "8672fe8a51fc246fe8bea8b8d4e88c83"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21.1",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.2-sources.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.2-sources.jar",
          "size": 196430,
          "sha512": "4d583a9e582d8173009ed3369901ba1e5d37eb530e25eecdc93d00d38bdb006a887205914703fab87fcf0d2c5cbe198643a30db4c285c8c0d8afd34523e5c467",
          "sha256": "502c08678c45155a3d35d7ccb086c72f26a773a2c9b200aeb753a6583ef4ce9d",
          "sha1": "ba04b94ca99b652fc4409d00421d61e7a54970da",
          "md5": "87e147fd67016b9c6f2b82434a773263"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21.1",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourceconfigapi-fabric-1.21-2.1.2-javadoc.jar",
          "url": "resourceconfigapi-fabric-1.21-2.1.2-javadoc.jar",
          "size": 207035,
          "sha512": "22250324b6cbf917450938f7840f6edd97e48d5c1b27af3d3f447097947e4ca97122b58d93972211bb17cadd42d1757ce2b34a130ef578e53df8d729a754e177",
          "sha256": "bd3580767af1b4db41367750f4081cc72374d94e9c574c982a7d157a6e67de26",
          "sha1": "5a2d383d7fed7b67fe88a05dd50dccff3e819948",
          "md5": "353ec1e0253287ba00ccfbe71041f730"
        }
      ],
      "capabilities": [
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric-1.21.1",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi-fabric",
          "version": "1.21-2.1.2"
        },
        {
          "group": "net.xstopho.resourceconfigapi",
          "name": "resourceconfigapi",
          "version": "1.21-2.1.2"
        }
      ]
    }
  ]
}
