{
  "formatVersion": "1.1",
  "component": {
    "group": "net.xstopho.resourcelibrary",
    "module": "resourcelibrary-neoforge",
    "version": "1.20.5-1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "resourcelibrary-neoforge-1.20.5-1.3.0.jar",
          "url": "resourcelibrary-neoforge-1.20.5-1.3.0.jar",
          "size": 193942,
          "sha512": "836846785eac48a2c060ec9cb5887b23356c1a62b9a9e91941dc71f559e81a087fb54ecd68061391490c9713f10b6011b3f824441453f60a3574d79dfb8c43a3",
          "sha256": "e9e21faf90b56c6ec6832df51ff8396cbe6e03ad097f9369478b59023e09b469",
          "sha1": "27db796a2d37dc3bbcf879a433bf5de102cd2777",
          "md5": "27986d3bb72de78b0cd2728708a6176d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourcelibrary-neoforge-1.20.5-1.3.0.jar",
          "url": "resourcelibrary-neoforge-1.20.5-1.3.0.jar",
          "size": 193942,
          "sha512": "836846785eac48a2c060ec9cb5887b23356c1a62b9a9e91941dc71f559e81a087fb54ecd68061391490c9713f10b6011b3f824441453f60a3574d79dfb8c43a3",
          "sha256": "e9e21faf90b56c6ec6832df51ff8396cbe6e03ad097f9369478b59023e09b469",
          "sha1": "27db796a2d37dc3bbcf879a433bf5de102cd2777",
          "md5": "27986d3bb72de78b0cd2728708a6176d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourcelibrary-neoforge-1.20.5-1.3.0-sources.jar",
          "url": "resourcelibrary-neoforge-1.20.5-1.3.0-sources.jar",
          "size": 174185,
          "sha512": "8f392acfffef2f5579ad4b647ed902ce60e29574899b5c6c7d052ea057c8c4cc1faafa1470d8c2bb63bce6a5e3677c0767cd9deddea862270c0359b88ba5a1b1",
          "sha256": "d942d9c32a07bffa750d1ab1d410a03d671eaf2155e943f072587ee7c52d450c",
          "sha1": "3082edc203652eccf7fd8892aec2520c9556b194",
          "md5": "04111a4eb07cc627a191976964542f3a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resourcelibrary-neoforge-1.20.5-1.3.0-javadoc.jar",
          "url": "resourcelibrary-neoforge-1.20.5-1.3.0-javadoc.jar",
          "size": 183030,
          "sha512": "f0c0e38d48fe7d5380b9582672103e9bb99f1efaf1836ed842ea2ed86328a3c2c2791164ee307f551544ad34ed2322290c4f48cd8c1fddb03dabab14f1ed0cb8",
          "sha256": "07f3e9c3494e03fdaa14d11018bc022877a7a80e6d7e7d5555ba5fef6a94eb53",
          "sha1": "9b4a6057a78ebdab6437dd37e749503e01097247",
          "md5": "0317949b286b4bc25626f6f6f6ede4f1"
        }
      ]
    }
  ]
}
